apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: br4cwew54-go 
  janus-idp.io/tekton: br4cwew54-go
  backstage.io/kubernetes-id: br4cwew54-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: br4cwew54-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml