apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: br4cwew54-go
  janus-idp.io/tekton: br4cwew54-go
  backstage.io/kubernetes-id: br4cwew54-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: br4cwew54-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
